"""Figure specifications shared by every manual language.

Each figure is captured once per UI language (en, lb).  Annotations are
located by UI string (namespace.key, resolved from the app's own message
catalogues), by ARIA label, or by CSS selector, then numbered on the image.
"""
# Locator forms:  ("t", "Ns.key")  exact visible text      ("tc", "Ns.key")  text contains
#                 ("aria", "Ns.key") aria-label            ("css", "selector")
#                 ("role", "button", "Ns.key")             ("ph", "Ns.key") placeholder
# Each annotation may be a tuple or a dict {"loc": ..., "nth": 0, "pad": 4}
# crop_sel: CSS selector; the capture is cut to that element plus 24 px
# trim (default True): cut empty background off the bottom of each capture
# steps: list of ("click", loc) / ("fill", loc, value) / ("wait", ms) / ("hover", loc) / ("press", key)

FIGS = [
 dict(id="signin", user="-", path="login", h=760,
      ann=[("css", "button[aria-label]"), ("css", "#login-username"), ("css", "#login-password"), ("css", "button[type=submit]")]),
 dict(id="shell", user="anne.reding", path="dashboard/club", h=900,
      ann=[("css", "aside nav"), ("css", "header button[role=combobox]"), ("css", "header .hidden.sm\\:flex"),
           {"loc": ("css", "header button[role=combobox]"), "nth": 1}, ("t", "Common.signOut"), ("aria", "Common.sidebarCollapse")]),
 dict(id="cover", user="anne.reding", path="dashboard/club", h=900, ann=[]),
 dict(id="club-overview", user="anne.reding", path="dashboard/club", h=900, clip_main=True,
      ann=[("t", "ClubAdmin.refreshAction"), ("t", "ClubAdmin.actionQueueTitle")]),
 dict(id="members-list", user="anne.reding", path="dashboard/club/members", h=760, clip_main=True,
      ann=[("ph", "ClubAdmin.searchMembersPlaceholder"), ("aria", "ClubAdmin.membersStatusFilterAriaLabel"),
           ("role", "button", "ClubAdmin.membersMenuLabel"), ("role", "button", "Common.batchActionsLabel"),
           {"loc": ("aria", "Common.selectRowLabel"), "nth": 0}, {"loc": ("aria", "ClubAdmin.deleteAction"), "nth": 0}]),
 dict(id="members-actions", user="anne.reding", path="dashboard/club/members", h=620, clip_main=True,
      steps=[("click", {"loc": ("aria", "Common.selectRowLabel"), "nth": 1}), ("click", {"loc": ("aria", "Common.selectRowLabel"), "nth": 2}),
             ("click", ("role", "button", "Common.batchActionsLabel")), ("wait", 500)],
      ann=[("t", "ClubAdmin.actionPrintCards"), ("t", "ClubAdmin.actionOrderLicense"), ("t", "ClubAdmin.actionChangeStatus"), ]),
 dict(id="members-menu", user="anne.reding", path="dashboard/club/members", h=520, clip_main=True,
      steps=[("click", ("role", "button", "ClubAdmin.membersMenuLabel")), ("wait", 500)],
      ann=[("t", "ClubAdmin.createMember"), ("t", "Import.importMembers")]),
 dict(id="member-detail", user="anne.reding", path="dashboard/club/members/60", h=820, clip_main=True,
      ann=[("t", "ClubAdmin.memberOverviewTab"), ("t", "ClubAdmin.memberClubRecordTab"), ("t", "ClubAdmin.memberCurrentLicensesTab"),
           ("t", "ClubAdmin.memberLicenseHistoryTab"), ("t", "ClubAdmin.memberGradesTab"), ("t", "ClubAdmin.memberClubMovementsTab"),
           ("aria", "ClubAdmin.editAction"), ("t", "ClubAdmin.photoChangeButton"), ("t", "ClubAdmin.downloadStatementAction")]),
 dict(id="member-record", user="anne.reding", path="dashboard/club/members/60", h=1500, clip_main=True,
      steps=[("click", ("t", "ClubAdmin.memberClubRecordTab")), ("wait", 1500)],
      ann=[("tc", "ClubMgmt.deliveryLabel"), ("tc", "ClubMgmt.memberFeeLabel"), ("tc", "ClubMgmt.paysLicenseFee"), ("tc", "ClubMgmt.contacts")]),
 dict(id="member-licence", user="anne.reding", path="dashboard/club/members/60", h=800, clip_main=True,
      steps=[("click", ("t", "ClubAdmin.memberCurrentLicensesTab")), ("wait", 2500)], ann=[]),
 dict(id="member-grades", user="anne.reding", path="dashboard/club/members/60", h=700, clip_main=True,
      steps=[("click", ("t", "ClubAdmin.memberGradesTab")), ("wait", 1200)], ann=[("aria", "ClubAdmin.addGradeAction")]),
 dict(id="member-new", user="anne.reding", path="dashboard/club/members/new", h=900, clip_main=True,
      steps=[("fill", ("css", "#member-first-name"), "Lena"), ("fill", ("css", "#member-last-name"), "KIEFFER"),
             ("click", {"loc": ("css", "main button[role=combobox]"), "nth": 1}), ("click", ("role", "option", "ClubAdmin.sexFemale")),
             ("fill", ("css", "#member-wt-license"), "LUX-48213"), ("fill", ("css", "#member-dob"), "14.03.2015"),
             ("click", {"loc": ("css", "main button[role=combobox]"), "nth": 3}), ("click", ("role", "option", "ClubAdmin.licenseRoleAthlete")),
             ("wait", 400)],
      ann=[]),
 dict(id="import", user="anne.reding", path="dashboard/club/members/import", h=900, clip_main=True, ann=[]),
 dict(id="order-licenses", user="anne.reding", path="dashboard/club/members?filter=missing", h=900, clip_main=True,
      steps=[("goto", "dashboard/club/members"), ("click", {"loc": ("aria", "Common.selectRowLabel"), "nth": 1}),
             ("click", {"loc": ("aria", "Common.selectRowLabel"), "nth": 18}), ("click", ("role", "button", "Common.batchActionsLabel")),
             ("click", ("t", "ClubAdmin.actionOrderLicense")), ("wait", 2500)], ann=[]),
 dict(id="licences", user="anne.reding", path="dashboard/club/licenses", h=700, clip_main=True, ann=[]),
 dict(id="print-jobs", user="anne.reding", path="dashboard/club/members", h=901, clip_main=True,
      steps=[("goto", "dashboard/club/members"), ("click", {"loc": ("aria", "Common.selectRowLabel"), "nth": 1}), ("click", {"loc": ("aria", "Common.selectRowLabel"), "nth": 2}),
             ("click", ("role", "button", "Common.batchActionsLabel")), ("click", ("t", "ClubAdmin.actionPrintCards")), ("wait", 3000)], ann=[]),
 dict(id="print-history", user="anne.reding", path="dashboard/club/print-jobs", h=700, clip_main=True, ann=[]),
 dict(id="transfers", user="anne.reding", path="dashboard/club/transfers", h=980, clip_main=True, ann=[]),
 dict(id="transfer-request", user="anne.reding", path="dashboard/club/transfers", h=900, modal=True,
      steps=[("click", ("css", "text=Sven BAUSCH")), ("click", ("css", "text=Dojang Musel (Demo)")), ("wait", 600)], ann=[]),
 dict(id="transfers-in", user="paul.musel", path="dashboard/club/transfers", h=2300, clip_main=True,
      crop_from=("t", "ClubAdmin.transferInboxTitle"),
      steps=[("click", ("css", "button:has-text('Leo SCHMIT')")), ("wait", 600)],
      ann=[("ph", "ClubAdmin.transferMessagePlaceholder"), ("t", "ClubAdmin.transferSendMessage"), ("t", "ClubAdmin.transferAcceptAction"), ("t", "ClubAdmin.transferRejectAction")]),
 dict(id="families", user="anne.reding", path="dashboard/club/families", h=900, clip_main=True, ann=[]),
 dict(id="fees", user="anne.reding", path="dashboard/club/fees", h=760, clip_main=True, ann=[]),
 dict(id="billing", user="anne.reding", path="dashboard/club/billing", h=900, w=1600, clip_main=True,
      ann=[("t", "ClubAdmin.navBilling"), {"loc": ("t", "ClubMgmt.billingYear"), "nth": 0}, ("t", "ClubMgmt.printPackAction"), ("t", "ClubMgmt.reviewIssueAction"),
           ("t", "ClubMgmt.selectReady"), ("aria", "ClubMgmt.billingFilterAria"), {"loc": ("t", "ClubMgmt.billingBlocked"), "nth": 0}]),
 dict(id="invoices", user="anne.reding", path="dashboard/club/invoices", h=760, w=1600, clip_main=True, ann=[]),
 dict(id="record-payment", user="anne.reding", path="dashboard/club/payments/5/record", h=900, clip_main=True, ann=[]),
 dict(id="reports", user="anne.reding", path="dashboard/club/reports", h=900, w=1600, clip_main=True, ann=[]),
 dict(id="bank", user="anne.reding", path="dashboard/club/bank", h=1100, w=1600, clip_main=True, ann=[]),
 dict(id="subsidies", user="anne.reding", path="dashboard/club/subsidies", h=1000, w=1600, clip_main=True, ann=[]),
 dict(id="training-week", user="anne.reding", path="dashboard/club/training", h=900, clip_main=True,
      ann=[("aria", "ClubAdmin.trainingTabsAriaLabel"), ("t", "ClubAdmin.trainingAddSession"), {"loc": ("t", "ClubAdmin.trainingOpenRoll"), "nth": 2},
           {"loc": ("t", "ClubAdmin.trainingCancel"), "nth": 2}]),
 dict(id="roll", user="anne.reding", path="dashboard/club/training/sessions/4", h=1000, clip_main=True,
      ann=[("tc", "ClubAdmin.trainingSessionCoaches"), ("t", "ClubAdmin.trainingAge_all"), ("tc", "ClubAdmin.trainingOnTheRoll"),
           ("t", "ClubAdmin.trainingMarkShown"), ("t", "ClubAdmin.trainingSaveRoll"), ("tc", "ClubAdmin.trainingAddStudents")]),
 dict(id="timetable", user="anne.reding", path="dashboard/club/training/timetable", h=1000, clip_main=True, ann=[]),
 dict(id="holidays", user="anne.reding", path="dashboard/club/training/holidays", h=800, clip_main=True, ann=[]),
 dict(id="coach-pay", user="anne.reding", path="dashboard/club/training/hours", h=1000, clip_main=True, ann=[]),
 dict(id="month", user="anne.reding", path="dashboard/club/training/month", h=900, clip_main=True, ann=[]),
 dict(id="promotion", user="anne.reding", path="dashboard/club/promotion", h=900, clip_main=True, ann=[]),
 dict(id="belt-test", user="anne.reding", path="dashboard/club/promotion/1", h=900, clip_main=True, ann=[]),
 dict(id="shop-sell", user="anne.reding", path="dashboard/club/shop/sell", h=900, clip_main=True,
      ann=[("aria", "ClubMgmt.shopTabsAria"), ("t", "ClubMgmt.shopScanCamera"), ("tc", "ClubMgmt.shopBasket")]),
 dict(id="shop-items", user="anne.reding", path="dashboard/club/shop/items", h=760, clip_main=True, ann=[]),
 dict(id="shop-item", user="anne.reding", path="dashboard/club/shop/items/1", h=1200, clip_main=True, ann=[]),
 dict(id="calendar", user="anne.reding", path="dashboard/club/calendar", h=1000,
      ann=[("t", "Events.calendarNew"), ("aria", "Events.calendarPrevMonth"), ("aria", "Events.calendarNextMonth"), ("css", "aside a[href$='/calendar']")]),
 dict(id="event-form", user="anne.reding", path="dashboard/club/calendar/new", h=1100, clip_main=True,
      ann=[("tc", "Events.calendarFieldVisibility")]),
 dict(id="club-profile", user="anne.reding", path="dashboard/club/settings", h=900, clip_main=True,
      ann=[("t", "ClubAdmin.clubSettingsProfileTab"), ("t", "ClubAdmin.clubSettingsTrainersTab"), ("t", "ClubAdmin.clubSettingsCommitteeTab"), ("t", "ClubAdmin.clubSettingsPublicationTab")]),
 dict(id="club-coaches", user="anne.reding", path="dashboard/club/settings", h=820, clip_main=True,
      steps=[("click", ("t", "ClubAdmin.clubSettingsTrainersTab")), ("wait", 1200)], ann=[]),
 dict(id="committee", user="anne.reding", path="dashboard/club/settings", h=820, clip_main=True,
      steps=[("click", ("t", "ClubAdmin.clubSettingsCommitteeTab")), ("wait", 1200)], ann=[]),
 dict(id="privacy", user="anne.reding", path="settings/privacy", h=700, crop_sel="main > div", trim=False, ann=[]),
 dict(id="club-admins", user="anne.reding", path="dashboard/club/admins", h=900, clip_main=True, ann=[]),
 dict(id="coach-week", user="jeff.lorang", path="dashboard/club/training", h=640, ann=[]),
 dict(id="ltf-overview", user="ltf.admin", path="dashboard/ltf", h=1000, ann=[]),
 dict(id="ltf-clubs", user="ltf.admin", path="dashboard/ltf/clubs", h=600, clip_main=True, ann=[]),
 dict(id="ltf-club", user="ltf.admin", path="dashboard/ltf/clubs/2", h=1100, clip_main=True, ann=[]),
 dict(id="ltf-club-admins", user="ltf.admin", path="dashboard/ltf/club-admins", h=900, clip_main=True, ann=[]),
 dict(id="ltf-transfers", user="ltf.admin", path="dashboard/ltf/member-transfers", h=900, clip_main=True, ann=[]),
 dict(id="ltf-licences", user="ltf.admin", path="dashboard/ltf/licenses", h=700, clip_main=True, ann=[]),
 dict(id="ltf-cards", user="ltf.admin", path="dashboard/ltf/license-cards", h=520, clip_main=True, ann=[]),
 dict(id="designer", user="ltf.admin", path="dashboard/ltf/license-cards/1/designer", h=900, w=1600, ann=[]),
 dict(id="ltf-print-jobs", user="ltf.admin", path="dashboard/ltf/license-cards/print-jobs", h=700, clip_main=True, ann=[]),
 dict(id="ltf-settings", user="ltf.admin", path="dashboard/ltf/settings", h=1100, clip_main=True, ann=[]),
 dict(id="ltf-calendar-form", user="ltf.admin", path="dashboard/ltf/calendar/new", h=1100, clip_main=True, ann=[]),
 dict(id="fin-overview", user="ltf.finance", path="dashboard/ltf-finance", h=1000, ann=[]),
 dict(id="fin-invoice", user="ltf.finance", path="dashboard/ltf-finance/invoices/14", h=1100, clip_main=True, ann=[]),
 dict(id="fin-settings", user="ltf.finance", path="dashboard/ltf-finance/license-settings", h=760, clip_main=True, ann=[]),
 dict(id="fin-billing", user="ltf.finance", path="dashboard/ltf-finance/license-settings?tab=billing", h=1000, clip_main=True, ann=[]),
 dict(id="fin-reports", user="ltf.finance", path="dashboard/ltf-finance/reports", h=1000, w=1600, clip_main=True, ann=[]),
 dict(id="ops-modules", user="ops.demo", path="dashboard/ops/modules", h=1100, clip_main=True, ann=[]),
]
