# Generated by Django 6.0.8 on 2026-09-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmgmt', '0002_membership_fee_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecord',
            name='invoice_delivery',
            field=models.CharField(choices=[('email', 'Email'), ('post', 'Post'), ('hand', 'In person')], default='email', max_length=10),
        ),
    ]
