# Generated by Django 6.0.8 on 2026-09-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmgmt', '0003_invoice_delivery_and_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrecord',
            name='membership_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_records', to='clubmgmt.membershipfee'),
        ),
    ]
