# Generated by Django 6.0.8 on 2026-09-24 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmgmt', '0010_subsidy_files_and_costs'),
        ('clubs', '0010_club_trainers'),
        ('members', '0015_capitalize_member_license_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
            ],
            options={
                'ordering': ['starts_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('audience', models.CharField(choices=[('kids', 'Kids'), ('adults', 'Adults'), ('belt_test', 'Belt-test preparation'), ('competition', 'Competition preparation'), ('other', 'Other')], max_length=20)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('skip_public_holidays', models.BooleanField(default=True)),
                ('skip_school_holidays', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_series', to='clubs.club')),
                ('coaches', models.ManyToManyField(blank=True, related_name='training_series_coached', to=settings.AUTH_USER_MODEL)),
                ('regulars', models.ManyToManyField(blank=True, related_name='training_series', to='members.member')),
            ],
            options={
                'ordering': ['weekday', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('audience', models.CharField(choices=[('kids', 'Kids'), ('adults', 'Adults'), ('belt_test', 'Belt-test preparation'), ('competition', 'Competition preparation'), ('other', 'Other')], max_length=20)),
                ('held_on', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('held', 'Held'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='clubs.club')),
                ('coaches', models.ManyToManyField(blank=True, related_name='training_sessions_coached', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clubmgmt.trainingseries')),
            ],
            options={
                'ordering': ['held_on', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_attendances', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_attendance_recorded', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='clubmgmt.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_payday_month', models.PositiveSmallIntegerField(default=6)),
                ('first_payday_day', models.PositiveSmallIntegerField(default=30)),
                ('second_payday_month', models.PositiveSmallIntegerField(default=12)),
                ('second_payday_day', models.PositiveSmallIntegerField(default=15)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_settings', to='clubs.club')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('series', 'held_on'), name='training_session_series_day'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingattendance',
            unique_together={('session', 'member')},
        ),
    ]
