# Generated by Django 6.0.8 on 2026-09-17 06:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_club_active_and_language'),
        ('licenses', '0042_credit_notes_reminders_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('ledger', models.CharField(choices=[('federation', 'Federation'), ('club', 'Club')], db_index=True, default='federation', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_format', models.CharField(choices=[('csv', 'CSV'), ('camt053', 'CAMT.053')], default='csv', max_length=20)),
                ('source_file', models.FileField(blank=True, upload_to='finance/bank-statements/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='clubs.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements_imported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('ignored', 'Ignored')], default='unmatched', max_length=20)),
                ('match_kind', models.CharField(blank=True, choices=[('payment', 'Payment'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_match', to='licenses.expense')),
                ('income', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_match', to='licenses.income')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_matches', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_match', to='licenses.payment')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='licenses.bankstatement')),
            ],
            options={
                'ordering': ['booked_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger', models.CharField(choices=[('federation', 'Federation'), ('club', 'Club')], db_index=True, default='federation', max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('license_fees', 'License / membership fees'), ('income', 'Other income'), ('expense', 'Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_budget_lines', to='clubs.club')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='licenses.expensecategory')),
                ('income_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='licenses.incomecategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_budget_lines_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['ledger', 'club', '-period_end'], name='bst_ledger_club_end_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['statement', 'status'], name='bstline_stmt_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='financebudgetline',
            constraint=models.UniqueConstraint(condition=models.Q(('club__isnull', False), ('kind', 'license_fees')), fields=('ledger', 'club', 'year', 'kind'), name='fin_budget_club_fees_uniq'),
        ),
        migrations.AddConstraint(
            model_name='financebudgetline',
            constraint=models.UniqueConstraint(condition=models.Q(('club__isnull', True), ('kind', 'license_fees')), fields=('ledger', 'year', 'kind'), name='fin_budget_fed_fees_uniq'),
        ),
        migrations.AddConstraint(
            model_name='financebudgetline',
            constraint=models.UniqueConstraint(condition=models.Q(('club__isnull', False), ('kind', 'income')), fields=('ledger', 'club', 'year', 'income_category'), name='fin_budget_club_inc_uniq'),
        ),
        migrations.AddConstraint(
            model_name='financebudgetline',
            constraint=models.UniqueConstraint(condition=models.Q(('club__isnull', True), ('kind', 'income')), fields=('ledger', 'year', 'income_category'), name='fin_budget_fed_inc_uniq'),
        ),
        migrations.AddConstraint(
            model_name='financebudgetline',
            constraint=models.UniqueConstraint(condition=models.Q(('club__isnull', False), ('kind', 'expense')), fields=('ledger', 'club', 'year', 'expense_category'), name='fin_budget_club_exp_uniq'),
        ),
        migrations.AddConstraint(
            model_name='financebudgetline',
            constraint=models.UniqueConstraint(condition=models.Q(('club__isnull', True), ('kind', 'expense')), fields=('ledger', 'year', 'expense_category'), name='fin_budget_fed_exp_uniq'),
        ),
    ]
