# Generated by Django 6.0.8 on 2026-09-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0043_bank_recon_and_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('post', 'Post'), ('hand', 'In person')], max_length=10),
        ),
    ]
